from app.seeders.catalog_helpers import ingredient as i
from app.seeders.catalog_helpers import recipe


def _kottu(name, protein, extras, method, diet_type="Omnivore", spice="Medium"):
    ingredients = [i("Godamba roti", 8, "piece"), i("Cabbage", 180, "g"), i("Carrot", 120, "g"), i("Leek", 100, "g"), i("Onion", 150, "g"), i("Curry gravy", 220, "ml"), i("Oil", 45, "ml"), i("Roasted curry powder", 15, "g"), i("Salt", 9, "g"), *extras]
    if protein and protein != "None":
        ingredients.insert(1, i(protein, 450 if protein != "Egg" else 4, "g" if protein != "Egg" else "piece"))
    return recipe(name, "kottu", "Kottu", f"A Sri Lankan griddle-chopped kottu finished with {method.rstrip('.').lower()}.", ingredients, ["Slice the godamba roti into narrow, even strips.", "Heat a wide griddle, add oil and soften onion before adding carrot, cabbage and leek.", f"{method}", "Add curry powder and gravy, then toss until the vegetables are seasoned but retain some bite.", "Add the roti strips and chop and fold rhythmically with two metal blades until evenly mixed.", "Cook only until the roti absorbs the gravy without becoming soggy, then serve immediately."], cuisine="Sri Lankan", region="Sri Lanka", protein=protein or "None", diet_type=diet_type, difficulty="Medium", prep_time=20, cook_time=20, spice_level=spice, tags=["kottu", "street food", "roti"])


def _fried_rice(name, protein, extras, method, cuisine="Sri Lankan", region="Sri Lanka", diet_type="Omnivore", spice="Mild"):
    ingredients = [i("Cooked long-grain rice", 700, "g"), i("Onion", 140, "g"), i("Garlic", 18, "g"), i("Carrot", 100, "g"), i("Spring onion", 45, "g"), i("Oil", 50, "ml"), i("Light soy sauce", 30, "ml"), i("Salt", 8, "g"), *extras]
    if protein and protein != "None":
        ingredients.insert(1, i(protein, 350 if protein not in {"Egg", "Prawn"} else (4 if protein == "Egg" else 400), "piece" if protein == "Egg" else "g"))
    return recipe(name, "fried-rice", "Rice Dishes", f"A {region} fried rice with separate grains and {method.rstrip('.').lower()}.", ingredients, ["Cook the rice ahead, spread it on a tray and cool completely so the grains firm up.", "Heat a wok until hot, add oil and cook the main protein separately until safely done; remove it.", "Stir-fry garlic, onion and carrot briefly on high heat.", method, "Add the cold rice in batches and toss rather than pressing it against the wok.", "Return the cooked protein, add soy sauce around the hot edge, season and finish with spring onion."], cuisine=cuisine, region=region, protein=protein or "None", diet_type=diet_type, prep_time=20, cook_time=18, spice_level=spice, tags=["fried rice", "quick meal", region.casefold()])


def _noodles(name, noodle, protein, extras, method, cuisine, region, diet_type="Omnivore", spice="Medium"):
    ingredients = [i(noodle, 450, "g"), i("Onion", 140, "g"), i("Garlic", 18, "g"), i("Carrot", 100, "g"), i("Cabbage", 140, "g"), i("Oil", 45, "ml"), i("Salt", 8, "g"), *extras]
    if protein and protein != "None":
        ingredients.insert(1, i(protein, 350 if protein != "Egg" else 4, "g" if protein != "Egg" else "piece"))
    return recipe(name, "noodles", "Noodles", f"A {region} noodle dish using {method.rstrip('.').lower()}.", ingredients, [f"Cook the {noodle.lower()} until just tender, rinse only if appropriate for the noodle, and drain thoroughly.", "Prepare all vegetables and sauce before heating the wok.", "Cook the protein separately over high heat until safely done and reserve it.", "Stir-fry garlic, onion, carrot and cabbage in stages so they stay crisp.", method, "Add noodles and protein, toss until the sauce coats every strand, and serve before the noodles soften."], cuisine=cuisine, region=region, protein=protein or "None", diet_type=diet_type, prep_time=20, cook_time=18, spice_level=spice, tags=["noodles", cuisine.casefold(), "quick meal"])


def _pasta(name, pasta, ingredients, method, region="Italy", protein="None", diet_type="Vegetarian", difficulty="Medium", cook_time=30):
    return recipe(name, "pasta", "Pasta", f"A distinct {region} pasta preparation built around {method.rstrip('.').lower()}.", [i(pasta, 400, "g"), i("Salt", 10, "g"), *ingredients], [f"Bring a large pot of salted water to a rolling boil and cook the {pasta.lower()} until al dente.", "Reserve some pasta water before draining.", method, "Add the pasta to the sauce and toss over heat, loosening gradually with reserved water.", "Check seasoning and sauce consistency, then serve immediately."], cuisine="Italian" if region == "Italy" else "International", region=region, protein=protein, diet_type=diet_type, difficulty=difficulty, prep_time=15, cook_time=cook_time, spice_level="Medium" if "chilli" in method.casefold() else "Mild", tags=["pasta", region.casefold()])


def staple_catalog():
    recipes = [
        # Kottu
        _kottu("Chicken Kottu", "Chicken", [i("Egg", 2, "piece")], "Stir-fry thin chicken strips until opaque and cooked through, then add beaten egg and scramble"),
        _kottu("Beef Kottu", "Beef", [i("Black pepper", 8, "g")], "Cook thin beef strips quickly with black pepper, keeping them tender before the final chop", spice="Hot"),
        _kottu("Mutton Kottu", "Mutton", [i("Mutton curry sauce", 150, "ml")], "Use tender cooked mutton pieces and their reduced curry sauce so the roti gains flavour without excess liquid", spice="Hot"),
        _kottu("Egg Kottu", "Egg", [i("Green chilli", 15, "g")], "Scramble the eggs softly with green chilli before folding in the vegetables", diet_type="Ovo-vegetarian"),
        _kottu("Vegetable Kottu", "None", [i("Green bean", 100, "g"), i("Bell pepper", 100, "g")], "Stir-fry green beans and bell pepper in addition to the base vegetables, keeping them bright", diet_type="Vegan"),
        _kottu("Cheese Kottu", "None", [i("Cheddar cheese", 180, "g"), i("Egg", 2, "piece")], "Scramble the egg, complete the chop, then add grated cheese off the fiercest heat so it melts without burning", diet_type="Vegetarian", spice="Mild"),
        _kottu("Chicken Cheese Kottu", "Chicken", [i("Cheddar cheese", 160, "g"), i("Egg", 2, "piece")], "Cook chicken and egg first; fold grated cheese through only during the final minute", spice="Mild"),
        _kottu("Masala Kottu", "None", [i("Tomato", 180, "g"), i("Garam masala", 10, "g"), i("Green chilli", 18, "g")], "Reduce tomato, green chilli and garam masala into a concentrated base before adding the vegetables", diet_type="Vegan", spice="Hot"),
        _kottu("Palandi Kottu", "Chicken", [i("Cream", 120, "ml"), i("Cheddar cheese", 120, "g"), i("Black pepper", 8, "g")], "Cook the chicken with black pepper, then finish the chopped kottu with cream and cheese for its characteristic rich sauce", spice="Mild"),

        # Hoppers and string hoppers
        recipe("Plain Hopper", "hoppers-appam", "Hoppers", "A crisp-edged Sri Lankan fermented rice and coconut bowl pancake.", [i("Rice flour", 400, "g"), i("Coconut milk", 500, "ml"), i("Active dry yeast", 7, "g"), i("Sugar", 12, "g"), i("Salt", 8, "g")], ["Whisk rice flour, yeast, sugar and enough coconut milk into a smooth batter.", "Ferment covered until lightly bubbly and aromatic.", "Thin with remaining coconut milk and add salt; the batter should coat and run.", "Heat a hopper pan, pour in batter and rotate once to form a thin lace rim and thicker centre.", "Cover and cook until the centre is set and the edge releases crisp."], cuisine="Sri Lankan", region="Sri Lanka", protein="None", diet_type="Vegan", difficulty="Medium", prep_time=480, cook_time=20, spice_level="None", tags=["hopper", "breakfast", "fermented"]),
        recipe("Egg Hopper", "hoppers-appam", "Hoppers", "A Sri Lankan hopper with a softly cooked egg in its tender centre.", [i("Rice flour", 400, "g"), i("Coconut milk", 500, "ml"), i("Active dry yeast", 7, "g"), i("Egg", 4, "piece"), i("Black pepper", 5, "g"), i("Salt", 8, "g")], ["Ferment the rice-flour and coconut-milk batter until bubbly.", "Heat and lightly oil a hopper pan, add batter and rotate to form the bowl.", "Crack one egg into the thicker centre without breaking the yolk.", "Season with pepper and salt, cover, and cook until the white is set and the rim crisp."], cuisine="Sri Lankan", region="Sri Lanka", protein="Egg", diet_type="Ovo-vegetarian", prep_time=480, cook_time=20, spice_level="Mild", tags=["hopper", "egg", "breakfast"]),
        recipe("Milk Hopper", "hoppers-appam", "Hoppers", "A soft Sri Lankan hopper filled with gently sweetened coconut milk.", [i("Rice flour", 400, "g"), i("Coconut milk", 650, "ml"), i("Active dry yeast", 7, "g"), i("Sugar", 35, "g"), i("Salt", 6, "g")], ["Ferment the basic rice and coconut batter until airy.", "Mix a portion of thick coconut milk with sugar and a pinch of salt.", "Swirl batter in the hot hopper pan and cook until the rim begins to set.", "Spoon sweet coconut milk into the centre, cover, and cook gently until custardy."], cuisine="Sri Lankan", region="Sri Lanka", protein="None", diet_type="Vegan", prep_time=480, cook_time=20, spice_level="None", tags=["hopper", "coconut milk", "breakfast"]),
        recipe("Jaggery Hopper", "hoppers-appam", "Hoppers", "A sweet hopper with coconut, kithul jaggery and warm cardamom.", [i("Rice flour", 400, "g"), i("Coconut milk", 550, "ml"), i("Active dry yeast", 7, "g"), i("Kithul jaggery", 120, "g"), i("Cardamom", 3, "g")], ["Ferment the hopper batter until bubbly.", "Melt jaggery with a splash of coconut milk, strain, and scent with cardamom.", "Swirl batter in the pan and let the edge set.", "Add jaggery coconut mixture to the centre, cover, and cook over low heat."], cuisine="Sri Lankan", region="Sri Lanka", protein="None", diet_type="Vegan", prep_time=480, cook_time=22, spice_level="None", tags=["hopper", "jaggery", "sweet"]),
        recipe("Kerala Appam", "hoppers-appam", "Hoppers", "A Kerala appam with a lacy edge and pillowy fermented centre.", [i("Raw rice", 400, "g"), i("Cooked rice", 100, "g"), i("Grated coconut", 120, "g"), i("Active dry yeast", 6, "g"), i("Sugar", 12, "g"), i("Salt", 8, "g")], ["Soak raw rice, then grind it very smooth with cooked rice and coconut.", "Add yeast and sugar and ferment until the batter rises and smells pleasantly sour.", "Thin to a flowing consistency and season with salt.", "Swirl in an appam pan, cover, and cook without flipping until the centre springs back."], cuisine="Indian", region="Kerala", protein="None", diet_type="Vegan", prep_time=600, cook_time=20, spice_level="None", tags=["appam", "fermented", "breakfast"]),
        recipe("White Rice String Hoppers", "string-hoppers", "Hoppers", "Soft steamed Sri Lankan white-rice flour noodle nests.", [i("Roasted white rice flour", 500, "g"), i("Boiling water", 550, "ml"), i("Salt", 8, "g")], ["Mix salt through the roasted rice flour.", "Add boiling water gradually and stir until a soft, pressable dough forms.", "Load the warm dough into a string-hopper press and pipe circles onto mats.", "Steam in batches until set and no dry flour remains."], cuisine="Sri Lankan", region="Sri Lanka", protein="None", diet_type="Vegan", difficulty="Medium", prep_time=25, cook_time=20, spice_level="None", tags=["string hoppers", "breakfast", "rice flour"]),
        recipe("Red Rice String Hoppers", "string-hoppers", "Hoppers", "Nutty steamed string hoppers made from Sri Lankan red-rice flour.", [i("Roasted red rice flour", 500, "g"), i("Boiling water", 580, "ml"), i("Salt", 8, "g")], ["Sift the red-rice flour and salt together.", "Work in boiling water until the dough is smooth and slightly firmer than white-rice dough.", "Press thin noodle coils onto string-hopper mats while warm.", "Steam until cooked through and lift only after a short rest."], cuisine="Sri Lankan", region="Sri Lanka", protein="None", diet_type="Vegan", prep_time=25, cook_time=22, spice_level="None", tags=["string hoppers", "red rice", "breakfast"]),
        recipe("Kurakkan String Hoppers", "string-hoppers", "Hoppers", "Earthy finger-millet string hoppers balanced with rice flour for a workable dough.", [i("Kurakkan flour", 300, "g"), i("Roasted rice flour", 200, "g"), i("Boiling water", 600, "ml"), i("Salt", 8, "g")], ["Sift kurakkan and rice flours together with salt.", "Add boiling water gradually and knead carefully into a smooth warm dough.", "Press immediately because millet dough firms as it cools.", "Steam until the nests are set and aromatic."], cuisine="Sri Lankan", region="Sri Lanka", protein="None", diet_type="Vegan", prep_time=25, cook_time=22, spice_level="None", tags=["string hoppers", "kurakkan", "millet"]),

        # Fried rice
        _fried_rice("Sri Lankan Fried Rice", "Chicken", [i("Egg", 2, "piece"), i("Leek", 80, "g"), i("Black pepper", 6, "g")], "Scramble the egg separately and season the rice with black pepper in the Sri Lankan banquet style"),
        _fried_rice("Chicken Fried Rice Variety", "Chicken", [i("Egg", 2, "piece"), i("Green pea", 90, "g")], "Stir-fry diced chicken separately and scramble egg before returning both to the rice", cuisine="Chinese", region="Chinese diaspora"),
        _fried_rice("Egg Fried Rice Variety", "Egg", [i("White pepper", 5, "g"), i("Sesame oil", 12, "ml")], "Scramble egg until barely set, add rice directly, and finish with white pepper and sesame oil", cuisine="Chinese", region="China", diet_type="Ovo-vegetarian"),
        _fried_rice("Vegetable Fried Rice Variety", "None", [i("Green pea", 100, "g"), i("Bell pepper", 100, "g"), i("Sweet corn", 90, "g")], "Stir-fry each vegetable quickly and keep its colour before adding the cooled rice", cuisine="Chinese", region="Chinese diaspora", diet_type="Vegan"),
        _fried_rice("Prawn Fried Rice", "Prawn", [i("Egg", 2, "piece"), i("White pepper", 5, "g")], "Sear prawns only until opaque, remove them, and return them after the rice is hot", cuisine="Chinese", region="Coastal China"),
        _fried_rice("Seafood Fried Rice", "Mixed seafood", [i("Egg", 2, "piece"), i("Fish sauce", 18, "ml")], "Cook firm seafood before delicate seafood and finish the rice with a small amount of fish sauce", cuisine="Southeast Asian", region="Southeast Asia"),
        _fried_rice("Beef Fried Rice", "Beef", [i("Black pepper", 7, "g"), i("Oyster sauce", 25, "ml")], "Velvet thin beef strips, sear quickly, and return with oyster sauce after the rice is hot", cuisine="Chinese", region="Chinese diaspora"),
        _fried_rice("Mixed Fried Rice", "Chicken", [i("Prawn", 220, "g"), i("Egg", 2, "piece"), i("Green pea", 90, "g")], "Cook chicken, prawn and egg separately so each reaches the right doneness before combining", cuisine="Sri Lankan", region="Sri Lanka"),
        _fried_rice("Chinese-style Fried Rice", "Egg", [i("Char siu", 180, "g"), i("Green pea", 90, "g"), i("Sesame oil", 12, "ml")], "Use a very hot wok, fry egg and rice together, then add diced char siu and peas", cuisine="Chinese", region="Cantonese", diet_type="Omnivore"),
        _fried_rice("Nasi Goreng Kampung", "Chicken", [i("Kecap manis", 45, "ml"), i("Sambal", 35, "g"), i("Shrimp paste", 8, "g")], "Fry sambal and shrimp paste until aromatic, then caramelize kecap manis around the rice", cuisine="Indonesian", region="Indonesia", spice="Hot"),

        # Noodles
        _noodles("Sri Lankan-style Noodles", "Wheat noodles", "Egg", [i("Leek", 80, "g"), i("Curry powder", 8, "g"), i("Soy sauce", 25, "ml")], "Season lightly with curry powder and soy sauce before folding through sliced leek", "Sri Lankan", "Sri Lanka", diet_type="Ovo-vegetarian"),
        _noodles("Chicken Noodles", "Egg noodles", "Chicken", [i("Soy sauce", 30, "ml"), i("Oyster sauce", 25, "ml")], "Toss with soy and oyster sauce after the chicken is cooked through", "Chinese", "Chinese diaspora"),
        _noodles("Egg Noodles", "Egg noodles", "Egg", [i("Soy sauce", 30, "ml"), i("Spring onion", 45, "g")], "Scramble eggs softly in the wok before tossing them through the noodles", "Chinese", "Chinese diaspora", diet_type="Ovo-vegetarian", spice="Mild"),
        _noodles("Vegetable Noodles", "Wheat noodles", "None", [i("Bell pepper", 100, "g"), i("Soy sauce", 30, "ml"), i("Sesame oil", 12, "ml")], "Stir-fry bell pepper with the vegetables and finish with sesame oil", "Chinese", "Chinese diaspora", diet_type="Vegan", spice="Mild"),
        _noodles("Seafood Noodles", "Egg noodles", "Mixed seafood", [i("Fish sauce", 20, "ml"), i("Bell pepper", 100, "g")], "Add seafood in order of cooking time and toss with fish sauce only after it turns opaque", "Southeast Asian", "Southeast Asia"),
        _noodles("Singapore Noodles", "Rice vermicelli", "Prawn", [i("Egg", 2, "piece"), i("Curry powder", 16, "g"), i("Bell pepper", 120, "g")], "Bloom curry powder briefly, then toss soaked vermicelli with prawn, egg and pepper", "Cantonese diaspora", "Hong Kong", spice="Medium"),
        _noodles("Chicken Chow Mein", "Egg noodles", "Chicken", [i("Bean sprout", 140, "g"), i("Oyster sauce", 25, "ml"), i("Sesame oil", 12, "ml")], "Sear the noodles for light wok char before tossing with chicken, bean sprouts and sauce", "Chinese", "China"),
        _noodles("Vegetable Chow Mein", "Egg noodles", "None", [i("Bean sprout", 160, "g"), i("Bell pepper", 100, "g"), i("Oyster sauce", 25, "ml")], "Sear the noodles, then add crisp vegetables and bean sprouts at the end", "Chinese", "China", diet_type="Vegetarian", spice="Mild"),
        _noodles("Pad Thai", "Rice noodles", "Prawn", [i("Egg", 2, "piece"), i("Tamarind paste", 45, "g"), i("Fish sauce", 35, "ml"), i("Palm sugar", 30, "g"), i("Peanut", 60, "g")], "Balance tamarind, fish sauce and palm sugar, then toss with egg and finish with crushed peanut", "Thai", "Thailand", spice="Medium"),

        # Pasta
        _pasta("Spaghetti Bolognese", "Spaghetti", [i("Minced beef", 500, "g"), i("Tomato passata", 500, "g"), i("Carrot", 100, "g"), i("Celery", 80, "g"), i("Olive oil", 35, "ml")], "Brown beef after softening the soffritto, add passata, and simmer the ragù slowly before tossing", protein="Beef", diet_type="Omnivore", cook_time=75),
        _pasta("Carbonara", "Spaghetti", [i("Guanciale", 180, "g"), i("Egg", 4, "piece"), i("Pecorino Romano", 120, "g"), i("Black pepper", 8, "g")], "Render guanciale; off direct heat emulsify egg, pecorino, pepper and pasta water without scrambling", region="Rome", protein="Pork", diet_type="Omnivore", difficulty="Advanced", cook_time=25),
        _pasta("Chicken Alfredo", "Fettuccine", [i("Chicken breast", 450, "g"), i("Butter", 70, "g"), i("Cream", 300, "ml"), i("Parmesan", 120, "g")], "Sear sliced chicken, reduce cream with butter, and melt parmesan gently before returning the chicken", region="Italian-American", protein="Chicken", diet_type="Omnivore"),
        _pasta("Fettuccine Alfredo", "Fettuccine", [i("Butter", 100, "g"), i("Parmesan", 150, "g"), i("Black pepper", 5, "g")], "Emulsify butter, finely grated parmesan and hot pasta water directly with the fettuccine", region="Rome", protein="None", diet_type="Vegetarian", difficulty="Medium", cook_time=20),
        _pasta("Penne Arrabbiata", "Penne", [i("Tomato", 500, "g"), i("Garlic", 20, "g"), i("Dried red chilli", 10, "g"), i("Olive oil", 45, "ml")], "Gently toast garlic and chilli in olive oil, add tomato, and reduce to a bright spicy sauce", region="Rome", protein="None", diet_type="Vegan", cook_time=30),
        _pasta("Spaghetti Aglio e Olio", "Spaghetti", [i("Garlic", 30, "g"), i("Olive oil", 80, "ml"), i("Dried red chilli", 6, "g"), i("Parsley", 25, "g")], "Cook sliced garlic slowly until pale gold, add chilli, then emulsify olive oil with starchy water", region="Naples", protein="None", diet_type="Vegan", difficulty="Medium", cook_time=20),
        _pasta("Pesto Pasta", "Fusilli", [i("Fresh basil", 80, "g"), i("Pine nut", 45, "g"), i("Parmesan", 90, "g"), i("Olive oil", 100, "ml")], "Pound or blend basil, pine nuts and parmesan without heating them, then loosen pesto with pasta water", region="Liguria", protein="None", diet_type="Vegetarian", cook_time=20),
        _pasta("Sri Lankan Chicken Pasta", "Penne", [i("Chicken", 450, "g"), i("Tomato", 350, "g"), i("Roasted curry powder", 12, "g"), i("Coconut milk", 180, "ml")], "Brown curry-spiced chicken, reduce tomato, and add coconut milk for a Sri Lankan-style sauce", region="Sri Lanka", protein="Chicken", diet_type="Omnivore", cook_time=35),
        _pasta("Seafood Pasta", "Spaghetti", [i("Mixed seafood", 550, "g"), i("Tomato", 400, "g"), i("Garlic", 25, "g"), i("Olive oil", 50, "ml")], "Cook seafood in stages, remove it, reduce the garlicky tomato sauce, then return it briefly", region="Coastal Italy", protein="Seafood", diet_type="Omnivore", cook_time=35),
        _pasta("Macaroni and Cheese", "Macaroni", [i("Cheddar cheese", 280, "g"), i("Milk", 600, "ml"), i("Butter", 60, "g"), i("Flour", 55, "g"), i("Mustard powder", 5, "g")], "Cook flour in butter, whisk in milk until smooth, then melt cheese off high heat before combining", region="International", protein="None", diet_type="Vegetarian", cook_time=35),
    ]
    return recipes
