from app.seeders.catalog_helpers import curry
from app.seeders.catalog_helpers import ingredient as i


def curry_catalog():
    return [
        # Chicken curry family
        curry("Sri Lankan Chicken Curry (Kukul Mas Curry)", "chicken-curry", "Chicken", 800, "Sri Lankan", "Sri Lanka", [i("Roasted curry powder", 25, "g"), i("Curry leaves", 12, "g"), i("Pandan leaf", 2, "piece"), i("Goraka", 12, "g")], "Toast the roasted curry powder with curry leaves and pandan, then reduce tomato before adding the chicken", liquid=("Coconut milk", 350, "ml"), protein="Chicken", spice_level="Hot", cook_time=45),
        curry("Jaffna-style Chicken Curry", "chicken-curry", "Chicken", 800, "Sri Lankan Tamil", "Jaffna", [i("Jaffna curry powder", 30, "g"), i("Fennel seed", 8, "g"), i("Curry leaves", 12, "g"), i("Tamarind", 20, "g")], "Fry the fennel-rich Jaffna powder briefly and dissolve tamarind into the reduced masala", liquid=("Water", 350, "ml"), protein="Chicken", spice_level="Hot", cook_time=50),
        curry("Sri Lankan Coconut Chicken Curry", "chicken-curry", "Chicken", 800, "Sri Lankan", "Sri Lanka", [i("Unroasted curry powder", 22, "g"), i("Turmeric", 5, "g"), i("Curry leaves", 12, "g"), i("Pandan leaf", 2, "piece")], "Use unroasted spices for a lighter base and add thick coconut milk only after the chicken is nearly tender", liquid=("Coconut milk", 450, "ml"), protein="Chicken", spice_level="Medium", cook_time=45),
        curry("Chettinad Chicken Curry", "chicken-curry", "Chicken", 800, "Indian", "Chettinad, Tamil Nadu", [i("Black pepper", 12, "g"), i("Fennel seed", 10, "g"), i("Kalpasi", 2, "g"), i("Grated coconut", 80, "g")], "Dry-roast pepper, fennel and kalpasi, grind with coconut, and fry the paste until its oil separates", liquid=("Water", 350, "ml"), protein="Chicken", spice_level="Hot", cook_time=50),
        curry("Andhra Chicken Curry", "chicken-curry", "Chicken", 800, "Indian", "Andhra Pradesh", [i("Dried red chilli", 20, "g"), i("Poppy seed", 15, "g"), i("Coriander seed", 15, "g"), i("Tomato", 220, "g")], "Cook a bold chilli and poppy-seed masala until glossy before coating and simmering the chicken", liquid=("Water", 300, "ml"), protein="Chicken", spice_level="Hot", cook_time=45),
        curry("Kerala Chicken Curry", "chicken-curry", "Chicken", 800, "Indian", "Kerala", [i("Coconut oil", 45, "ml"), i("Curry leaves", 15, "g"), i("Black pepper", 10, "g"), i("Tomato", 180, "g")], "Temper curry leaves in coconut oil and reduce tomato with black pepper before adding the chicken", liquid=("Coconut milk", 350, "ml"), protein="Chicken", spice_level="Medium", cook_time=45),
        curry("Malabar Chicken Curry", "chicken-curry", "Chicken", 800, "Indian", "Malabar, Kerala", [i("Fennel seed", 9, "g"), i("Grated coconut", 100, "g"), i("Curry leaves", 12, "g"), i("Green chilli", 18, "g")], "Roast coconut with fennel until golden, grind it, and cook the paste into a fragrant coastal gravy", liquid=("Water", 350, "ml"), protein="Chicken", spice_level="Medium", cook_time=50),
        curry("Kori Gassi", "chicken-curry", "Chicken", 800, "Indian", "Mangaluru, Karnataka", [i("Dried red chilli", 18, "g"), i("Grated coconut", 120, "g"), i("Tamarind", 18, "g"), i("Coriander seed", 15, "g")], "Roast chillies, coconut and coriander, grind with tamarind, and simmer into a thick Mangalorean gassi", liquid=("Water", 350, "ml"), protein="Chicken", spice_level="Hot", cook_time=50),
        curry("Chicken Korma", "chicken-curry", "Chicken", 800, "Mughlai", "North India", [i("Yogurt", 250, "g"), i("Cashew", 60, "g"), i("Cardamom", 5, "g"), i("Saffron", 1, "g")], "Lower the heat before adding whisked yogurt and cashew paste so the pale aromatic gravy stays smooth", liquid=("Water", 220, "ml"), protein="Chicken", spice_level="Mild", cook_time=45),
        curry("Butter Chicken", "chicken-curry", "Chicken", 750, "Indian", "Delhi", [i("Tomato puree", 450, "g"), i("Butter", 80, "g"), i("Cream", 150, "ml"), i("Kasuri methi", 8, "g")], "Char the marinated chicken separately, strain the cooked tomato gravy, then finish with butter, cream and kasuri methi", protein="Chicken", spice_level="Mild", prep_time=35, cook_time=45),
        curry("Chicken Tikka Masala", "chicken-curry", "Chicken", 750, "British Indian", "United Kingdom", [i("Yogurt", 180, "g"), i("Tomato puree", 400, "g"), i("Garam masala", 15, "g"), i("Cream", 120, "ml")], "Grill the yogurt-marinated chicken until lightly charred and fold it into a robust tomato-onion masala", protein="Chicken", spice_level="Medium", prep_time=35, cook_time=40),
        curry("Thai Green Chicken Curry", "chicken-curry", "Chicken", 700, "Thai", "Central Thailand", [i("Green curry paste", 70, "g"), i("Thai basil", 25, "g"), i("Bamboo shoot", 180, "g"), i("Fish sauce", 35, "ml")], "Fry green curry paste in the coconut cream that rises first, then simmer chicken and bamboo shoots gently", liquid=("Coconut milk", 500, "ml"), protein="Chicken", spice_level="Hot", cook_time=30),
        curry("Thai Red Chicken Curry", "chicken-curry", "Chicken", 700, "Thai", "Central Thailand", [i("Red curry paste", 65, "g"), i("Thai basil", 25, "g"), i("Bell pepper", 180, "g"), i("Fish sauce", 35, "ml")], "Bloom red curry paste in coconut cream, cook the chicken, and add bell pepper late to retain colour", liquid=("Coconut milk", 500, "ml"), protein="Chicken", spice_level="Hot", cook_time=30),
        curry("Gulai Ayam", "chicken-curry", "Chicken", 800, "Indonesian", "Sumatra", [i("Lemongrass", 30, "g"), i("Galangal", 25, "g"), i("Candlenut", 40, "g"), i("Turmeric", 8, "g")], "Fry the candlenut, turmeric, galangal and lemongrass paste until aromatic before adding coconut milk", liquid=("Coconut milk", 500, "ml"), protein="Chicken", spice_level="Medium", cook_time=45),

        # Fish curry family
        curry("Sri Lankan Fish Curry", "fish-curry", "Firm fish", 800, "Sri Lankan", "Sri Lanka", [i("Roasted curry powder", 22, "g"), i("Goraka", 18, "g"), i("Curry leaves", 12, "g"), i("Pandan leaf", 2, "piece")], "Boil goraka with the roasted spice base before sliding in fish pieces and shaking the pan instead of stirring", liquid=("Water", 350, "ml"), protein="Fish", spice_level="Hot", cook_time=30),
        curry("Jaffna Fish Curry", "fish-curry", "Firm fish", 800, "Sri Lankan Tamil", "Jaffna", [i("Jaffna curry powder", 28, "g"), i("Tamarind", 25, "g"), i("Fenugreek seed", 5, "g"), i("Curry leaves", 12, "g")], "Temper fenugreek carefully, cook out the Jaffna powder, and build a sharp tamarind broth before adding fish", liquid=("Water", 400, "ml"), protein="Fish", spice_level="Hot", cook_time=30),
        curry("Ambul Thiyal", "fish-curry", "Tuna", 800, "Sri Lankan", "Southern Sri Lanka", [i("Goraka", 45, "g"), i("Black pepper", 18, "g"), i("Roasted curry powder", 18, "g"), i("Curry leaves", 12, "g")], "Coat tuna in a black goraka-pepper paste and cook covered with very little water until dry, dark and preserved", liquid=("Water", 160, "ml"), protein="Fish", spice_level="Hot", cook_time=40),
        curry("Coconut Fish Curry", "fish-curry", "White fish", 800, "Sri Lankan", "Coastal Sri Lanka", [i("Unroasted curry powder", 20, "g"), i("Turmeric", 5, "g"), i("Green chilli", 18, "g"), i("Curry leaves", 12, "g")], "Simmer the pale coconut gravy first and add fish only for the final gentle cook so it remains succulent", liquid=("Coconut milk", 450, "ml"), protein="Fish", spice_level="Medium", cook_time=25),
        curry("Kerala Fish Curry", "fish-curry", "King fish", 800, "Indian", "Kerala", [i("Kudampuli", 30, "g"), i("Kashmiri chilli powder", 18, "g"), i("Fenugreek seed", 4, "g"), i("Curry leaves", 12, "g")], "Steep kudampuli, temper fenugreek and curry leaves, then cook fish in the red clay-pot gravy without coconut milk", liquid=("Water", 400, "ml"), protein="Fish", spice_level="Hot", cook_time=30),
        curry("Goan Fish Curry", "fish-curry", "White fish", 800, "Indian", "Goa", [i("Grated coconut", 120, "g"), i("Kashmiri chilli", 18, "g"), i("Tamarind", 22, "g"), i("Coriander seed", 15, "g")], "Grind coconut, Kashmiri chilli, coriander and tamarind very smooth, cook the sauce, then poach the fish", liquid=("Water", 350, "ml"), protein="Fish", spice_level="Medium", cook_time=30),
        curry("Tamarind Fish Curry", "fish-curry", "Firm fish", 800, "South Indian", "Tamil Nadu", [i("Tamarind", 35, "g"), i("Tomato", 220, "g"), i("Fenugreek seed", 5, "g"), i("Chilli powder", 14, "g")], "Reduce tamarind water with tomato and fenugreek until the raw sourness softens before adding fish", liquid=("Water", 400, "ml"), protein="Fish", spice_level="Hot", cook_time=30),
        curry("Spicy Fish Curry", "fish-curry", "Firm fish", 800, "South Asian", "South Asia", [i("Chilli powder", 20, "g"), i("Black pepper", 12, "g"), i("Tomato", 220, "g"), i("Lemon juice", 30, "ml")], "Fry chilli and pepper into the tomato base, simmer until glossy, then poach the fish just through", liquid=("Water", 320, "ml"), protein="Fish", spice_level="Hot", cook_time=30),

        # Seafood curry family
        curry("Sri Lankan Prawn Curry", "seafood-curry", "Prawn", 700, "Sri Lankan", "Sri Lanka", [i("Roasted curry powder", 20, "g"), i("Curry leaves", 12, "g"), i("Pandan leaf", 2, "piece"), i("Tomato", 180, "g")], "Cook the coconut gravy until aromatic before adding prawns for only the final few minutes", liquid=("Coconut milk", 380, "ml"), protein="Prawn", spice_level="Hot", cook_time=25),
        curry("Jaffna Prawn Curry", "seafood-curry", "Prawn", 700, "Sri Lankan Tamil", "Jaffna", [i("Jaffna curry powder", 26, "g"), i("Tamarind", 22, "g"), i("Fennel seed", 7, "g"), i("Curry leaves", 12, "g")], "Develop the fennel-rich, tamarind Jaffna gravy first and cook prawns only until curled and opaque", liquid=("Water", 320, "ml"), protein="Prawn", spice_level="Hot", cook_time=25),
        curry("Coconut Prawn Curry", "seafood-curry", "Prawn", 700, "Sri Lankan", "Coastal Sri Lanka", [i("Turmeric", 5, "g"), i("Green chilli", 18, "g"), i("Lime juice", 25, "ml"), i("Curry leaves", 12, "g")], "Keep the coconut gravy at a gentle simmer and finish with lime after the prawns turn opaque", liquid=("Coconut milk", 450, "ml"), protein="Prawn", spice_level="Medium", cook_time=22),
        curry("Sri Lankan Crab Curry", "seafood-curry", "Crab", 1000, "Sri Lankan", "Sri Lanka", [i("Roasted curry powder", 28, "g"), i("Curry leaves", 15, "g"), i("Pandan leaf", 2, "piece"), i("Fenugreek seed", 5, "g")], "Crack the claws, coat every piece in roasted masala, and simmer until the shells redden and the gravy penetrates", liquid=("Coconut milk", 450, "ml"), protein="Crab", spice_level="Hot", cook_time=40),
        curry("Jaffna Crab Curry", "seafood-curry", "Crab", 1000, "Sri Lankan Tamil", "Jaffna", [i("Jaffna curry powder", 32, "g"), i("Tamarind", 28, "g"), i("Fennel seed", 9, "g"), i("Drumstick", 250, "g")], "Cook drumstick in the sharp Jaffna gravy first, then add cracked crab and turn carefully until shells are red", liquid=("Water", 450, "ml"), protein="Crab", spice_level="Hot", cook_time=45),
        curry("Cuttlefish Curry", "seafood-curry", "Cuttlefish", 800, "Sri Lankan", "Sri Lanka", [i("Roasted curry powder", 24, "g"), i("Goraka", 15, "g"), i("Curry leaves", 12, "g"), i("Black pepper", 10, "g")], "Cook cuttlefish either briefly or until tender; for this curry simmer steadily after the initial sear to avoid rubberiness", liquid=("Coconut milk", 350, "ml"), protein="Cuttlefish", spice_level="Hot", cook_time=40),
        curry("Mixed Seafood Curry", "seafood-curry", "Mixed seafood", 850, "Sri Lankan", "Coastal Sri Lanka", [i("Roasted curry powder", 22, "g"), i("Tamarind", 20, "g"), i("Curry leaves", 12, "g"), i("Tomato", 180, "g")], "Cook the sauce completely, add firm fish first, then prawns and delicate seafood in staggered stages", liquid=("Coconut milk", 400, "ml"), protein="Seafood", spice_level="Hot", cook_time=30),

        # Mutton curry family
        curry("Sri Lankan Mutton Curry", "mutton-curry", "Mutton", 850, "Sri Lankan", "Sri Lanka", [i("Roasted curry powder", 30, "g"), i("Curry leaves", 12, "g"), i("Pandan leaf", 2, "piece"), i("Goraka", 15, "g")], "Brown the mutton in roasted spices, then braise slowly with pandan and goraka until tender", liquid=("Coconut milk", 350, "ml"), protein="Mutton", spice_level="Hot", cook_time=85),
        curry("Jaffna Mutton Curry", "mutton-curry", "Mutton", 850, "Sri Lankan Tamil", "Jaffna", [i("Jaffna curry powder", 34, "g"), i("Fennel seed", 9, "g"), i("Tamarind", 20, "g"), i("Curry leaves", 12, "g")], "Fry the fennel-led Jaffna spice blend and braise the mutton in a reduced tamarind gravy", liquid=("Water", 450, "ml"), protein="Mutton", spice_level="Hot", cook_time=90),
        curry("South Indian Mutton Curry", "mutton-curry", "Mutton", 850, "Indian", "South India", [i("Coriander powder", 20, "g"), i("Chilli powder", 14, "g"), i("Tomato", 220, "g"), i("Curry leaves", 12, "g")], "Pressure-cook or slow-braise the mutton after frying a tomato and coriander masala until its oil releases", liquid=("Water", 450, "ml"), protein="Mutton", spice_level="Hot", cook_time=80),
        curry("Chettinad Mutton Curry", "mutton-curry", "Mutton", 850, "Indian", "Chettinad, Tamil Nadu", [i("Black pepper", 14, "g"), i("Fennel seed", 10, "g"), i("Kalpasi", 2, "g"), i("Grated coconut", 90, "g")], "Roast and grind pepper, fennel, kalpasi and coconut, then braise mutton in the dark aromatic paste", liquid=("Water", 450, "ml"), protein="Mutton", spice_level="Hot", cook_time=90),
        curry("Kerala Mutton Curry", "mutton-curry", "Mutton", 850, "Indian", "Kerala", [i("Coconut oil", 45, "ml"), i("Black pepper", 12, "g"), i("Curry leaves", 15, "g"), i("Grated coconut", 90, "g")], "Roast coconut until brown, grind it, and simmer with peppery mutton until the gravy is dark and glossy", liquid=("Water", 450, "ml"), protein="Mutton", spice_level="Hot", cook_time=90),
        curry("Mutton Korma", "mutton-curry", "Mutton", 850, "Mughlai", "North India", [i("Yogurt", 260, "g"), i("Cashew", 60, "g"), i("Cardamom", 5, "g"), i("Saffron", 1, "g")], "Braise the mutton gently in whisked yogurt and nut paste without browning the pale aromatic sauce too far", liquid=("Water", 350, "ml"), protein="Mutton", spice_level="Mild", cook_time=90),
        curry("Rogan Josh", "mutton-curry", "Lamb", 850, "Kashmiri", "Kashmir", [i("Kashmiri chilli powder", 18, "g"), i("Fennel powder", 12, "g"), i("Dry ginger powder", 8, "g"), i("Yogurt", 220, "g")], "Temper whole spices, add yogurt gradually, and braise lamb with fennel and dry ginger until the red gravy is silky", liquid=("Water", 400, "ml"), protein="Lamb", spice_level="Medium", cook_time=90),

        # Dhal and lentils
        curry("Sri Lankan Parippu Curry", "dhal-lentils", "Red lentils", 300, "Sri Lankan", "Sri Lanka", [i("Turmeric", 5, "g"), i("Curry leaves", 12, "g"), i("Mustard seed", 6, "g"), i("Green chilli", 15, "g")], "Boil lentils with turmeric until soft, add coconut milk, then finish with a separate mustard and curry-leaf temper", liquid=("Coconut milk", 300, "ml"), protein="None", diet_type="Vegan", spice_level="Mild", cook_time=30),
        curry("Sri Lankan Coconut Dhal", "dhal-lentils", "Red lentils", 300, "Sri Lankan", "Sri Lanka", [i("Turmeric", 5, "g"), i("Pandan leaf", 2, "piece"), i("Curry leaves", 12, "g"), i("Mustard seed", 6, "g")], "Cook lentils directly with thin coconut milk and pandan, then enrich with thick coconut milk and a crisp temper", liquid=("Coconut milk", 400, "ml"), protein="None", diet_type="Vegan", spice_level="Mild", cook_time=30),
        curry("Masoor Dal", "dhal-lentils", "Red lentils", 300, "Indian", "North India", [i("Turmeric", 5, "g"), i("Cumin seed", 7, "g"), i("Tomato", 180, "g"), i("Coriander leaves", 20, "g")], "Cook the lentils creamy, then pour over a cumin, tomato and garlic temper and fold once", liquid=("Water", 750, "ml"), protein="None", diet_type="Vegan", spice_level="Medium", cook_time=30),
        curry("Dal Tadka", "dhal-lentils", "Toor dal", 300, "Indian", "North India", [i("Cumin seed", 7, "g"), i("Dried red chilli", 8, "g"), i("Tomato", 180, "g"), i("Ghee", 35, "ml")], "Whisk the cooked dal smooth and finish at the table with a sizzling cumin, chilli and ghee tadka", liquid=("Water", 800, "ml"), protein="None", diet_type="Vegetarian", spice_level="Medium", cook_time=40),
        curry("Dal Fry", "dhal-lentils", "Toor dal", 300, "Indian", "North India", [i("Cumin seed", 7, "g"), i("Tomato", 200, "g"), i("Garam masala", 8, "g"), i("Coriander leaves", 20, "g")], "Fry onion and tomato masala thoroughly, stir in cooked dal, and simmer together so the flavours integrate", liquid=("Water", 750, "ml"), protein="None", diet_type="Vegetarian", spice_level="Medium", cook_time=40),
        curry("Dal Makhani", "dhal-lentils", "Whole black gram", 300, "Indian", "Punjab", [i("Kidney bean", 80, "g"), i("Tomato puree", 300, "g"), i("Butter", 70, "g"), i("Cream", 100, "ml")], "Soak and pressure-cook the pulses, then simmer them very slowly with tomato and butter until naturally creamy", liquid=("Water", 900, "ml"), protein="None", diet_type="Vegetarian", spice_level="Mild", prep_time=40, cook_time=120),
        curry("Sambar", "dhal-lentils", "Toor dal", 280, "South Indian", "South India", [i("Mixed vegetables", 450, "g"), i("Tamarind", 30, "g"), i("Sambar powder", 25, "g"), i("Mustard seed", 6, "g")], "Cook dal and vegetables separately, combine with tamarind and sambar powder, then finish with mustard and curry leaves", liquid=("Water", 900, "ml"), protein="None", diet_type="Vegan", spice_level="Medium", cook_time=45),

        # Vegetable curries
        curry("Sri Lankan Potato Curry", "vegetable-curries", "Potato", 700, "Sri Lankan", "Sri Lanka", [i("Unroasted curry powder", 18, "g"), i("Turmeric", 5, "g"), i("Curry leaves", 12, "g"), i("Pandan leaf", 2, "piece")], "Simmer potato gently with unroasted spices and pandan, adding thick coconut milk near the end", liquid=("Coconut milk", 400, "ml"), protein="None", diet_type="Vegan", spice_level="Mild", cook_time=35),
        curry("Brinjal Curry", "vegetable-curries", "Eggplant", 650, "South Asian", "South Asia", [i("Coriander powder", 15, "g"), i("Cumin powder", 8, "g"), i("Tomato", 200, "g"), i("Tamarind", 15, "g")], "Brown eggplant pieces separately, prepare the tomato spice gravy, then return them without breaking their shape", liquid=("Water", 250, "ml"), protein="None", diet_type="Vegan", spice_level="Medium", cook_time=35),
        curry("Sri Lankan Wambatu Curry", "vegetable-curries", "Eggplant", 650, "Sri Lankan", "Sri Lanka", [i("Roasted curry powder", 18, "g"), i("Mustard seed", 6, "g"), i("Curry leaves", 12, "g"), i("Tamarind", 18, "g")], "Lightly fry eggplant, temper mustard and curry leaves, then simmer briefly in a tangy coconut gravy", liquid=("Coconut milk", 350, "ml"), protein="None", diet_type="Vegan", spice_level="Medium", cook_time=35),
        curry("Sri Lankan Pumpkin Curry", "vegetable-curries", "Pumpkin", 750, "Sri Lankan", "Sri Lanka", [i("Unroasted curry powder", 16, "g"), i("Fenugreek seed", 4, "g"), i("Curry leaves", 12, "g"), i("Pandan leaf", 2, "piece")], "Cook pumpkin gently with thin coconut milk, then crush a few pieces to thicken the finished curry naturally", liquid=("Coconut milk", 400, "ml"), protein="None", diet_type="Vegan", spice_level="Mild", cook_time=30),
        curry("Ripe Jackfruit Curry", "vegetable-curries", "Ripe jackfruit", 750, "Sri Lankan", "Sri Lanka", [i("Unroasted curry powder", 16, "g"), i("Cinnamon", 4, "g"), i("Curry leaves", 12, "g"), i("Green chilli", 15, "g")], "Simmer the sweet jackfruit gently in a lightly spiced coconut gravy without breaking the soft fruit", liquid=("Coconut milk", 380, "ml"), protein="None", diet_type="Vegan", spice_level="Mild", cook_time=30),
        curry("Polos Curry", "vegetable-curries", "Young jackfruit", 900, "Sri Lankan", "Sri Lanka", [i("Roasted curry powder", 28, "g"), i("Goraka", 18, "g"), i("Curry leaves", 15, "g"), i("Pandan leaf", 2, "piece")], "Coat young jackfruit in roasted spices and slow-cook until fibres are tender and the dark gravy is absorbed", liquid=("Coconut milk", 450, "ml"), protein="None", diet_type="Vegan", spice_level="Hot", cook_time=75),
        curry("Sri Lankan Beetroot Curry", "vegetable-curries", "Beetroot", 650, "Sri Lankan", "Sri Lanka", [i("Unroasted curry powder", 15, "g"), i("Turmeric", 4, "g"), i("Curry leaves", 12, "g"), i("Green chilli", 15, "g")], "Cook thin beetroot batons until just tender, then reduce coconut milk until it coats them brightly", liquid=("Coconut milk", 320, "ml"), protein="None", diet_type="Vegan", spice_level="Mild", cook_time=30),
        curry("Okra Curry", "vegetable-curries", "Okra", 650, "South Asian", "South Asia", [i("Coriander powder", 15, "g"), i("Tomato", 200, "g"), i("Cumin seed", 7, "g"), i("Lemon juice", 25, "ml")], "Dry the okra thoroughly and fry it before adding to the reduced masala so it stays distinct rather than slimy", liquid=("Water", 180, "ml"), protein="None", diet_type="Vegan", spice_level="Medium", cook_time=30),
        curry("Chickpea Curry", "vegetable-curries", "Cooked chickpea", 700, "Indian", "North India", [i("Tomato", 250, "g"), i("Chana masala", 22, "g"), i("Amchur", 8, "g"), i("Cumin seed", 7, "g")], "Reduce the tomato and chana masala base well, then mash a few chickpeas to give the gravy body", liquid=("Water", 350, "ml"), protein="None", diet_type="Vegan", spice_level="Medium", cook_time=35),
        curry("Mushroom Curry", "vegetable-curries", "Mushroom", 650, "Indian", "South India", [i("Tomato", 200, "g"), i("Coriander powder", 15, "g"), i("Curry leaves", 12, "g"), i("Black pepper", 8, "g")], "Brown mushrooms in batches so they do not steam, then return them to the peppery reduced gravy", liquid=("Coconut milk", 300, "ml"), protein="None", diet_type="Vegan", spice_level="Medium", cook_time=30),
        curry("Mixed Vegetable Curry", "vegetable-curries", "Mixed vegetables", 800, "Sri Lankan", "Sri Lanka", [i("Unroasted curry powder", 18, "g"), i("Turmeric", 5, "g"), i("Curry leaves", 12, "g"), i("Pandan leaf", 2, "piece")], "Add dense vegetables first and delicate vegetables later, then finish the mild curry with thick coconut milk", liquid=("Coconut milk", 420, "ml"), protein="None", diet_type="Vegan", spice_level="Mild", cook_time=35),
    ]
