from app.seeders.catalog_helpers import biryani
from app.seeders.catalog_helpers import ingredient as i


def biryani_catalog():
    return [
        biryani("Sri Lankan Chicken Biryani", "Sri Lankan", "Sri Lanka", "Chicken", "Basmati rice", [i("Roasted Sri Lankan curry powder", 24, "g"), i("Pandan leaf", 2, "piece"), i("Coconut milk", 180, "ml")], "Cook the chicken with roasted curry powder, pandan and coconut milk until the gravy clings to the pieces"),
        biryani("Sri Lankan Mutton Biryani", "Sri Lankan", "Sri Lanka", "Mutton", "Basmati rice", [i("Roasted curry powder", 25, "g"), i("Pandan leaf", 2, "piece"), i("Cashew", 50, "g")], "Braise the mutton with roasted spices and pandan until nearly tender before it meets the rice", cook_time=80),
        biryani("Hyderabadi Chicken Biryani", "Indian", "Hyderabad", "Chicken", "Basmati rice", [i("Green chilli", 25, "g"), i("Lemon juice", 35, "ml"), i("Saffron milk", 80, "ml")], "Keep the yogurt-marinated chicken raw beneath 70-percent-cooked rice and seal for kacchi dum", spice_level="Hot", cook_time=65),
        biryani("Hyderabadi Mutton Biryani", "Indian", "Hyderabad", "Mutton", "Basmati rice", [i("Green chilli", 25, "g"), i("Raw papaya paste", 25, "g"), i("Saffron milk", 80, "ml")], "Tenderize the mutton with raw papaya, marinate deeply, then cook beneath parboiled rice in a sealed kacchi dum", spice_level="Hot", prep_time=50, cook_time=90),
        biryani("Lucknowi Awadhi Biryani", "Indian", "Lucknow, Awadh", "Mutton", "Basmati rice", [i("Mace", 2, "g"), i("Rose water", 12, "ml"), i("Mutton stock", 500, "ml")], "Cook a delicate yakhni stock first, strain it, and finish meat and rice separately before a fragrant pakki dum", spice_level="Mild", cook_time=85),
        biryani("Kolkata Biryani", "Indian", "Kolkata", "Mutton", "Basmati rice", [i("Potato", 400, "g"), i("Rose water", 12, "ml"), i("Meetha attar", 2, "ml")], "Brown whole potatoes, cook the mutton gently, and layer both with lightly spiced rice and restrained aromatics", spice_level="Mild", cook_time=80),
        biryani("Malabar Biryani", "Indian", "Malabar, Kerala", "Chicken", "Kaima rice", [i("Cashew", 45, "g"), i("Raisin", 35, "g"), i("Fennel seed", 8, "g")], "Make a moist fennel-led chicken masala and fold it with separately cooked short-grain kaima rice", spice_level="Medium", cook_time=55),
        biryani("Thalassery Biryani", "Indian", "Thalassery, Kerala", "Chicken", "Jeerakasala rice", [i("Cashew", 45, "g"), i("Raisin", 35, "g"), i("Fennel powder", 8, "g")], "Cook the chicken masala without chilli powder, perfume the jeerakasala rice, then layer briefly for dum", spice_level="Mild", cook_time=55),
        biryani("Dindigul Biryani", "Indian", "Dindigul, Tamil Nadu", "Chicken", "Seeraga samba rice", [i("Curd", 180, "g"), i("Lemon juice", 45, "ml"), i("Green chilli", 30, "g")], "Cook meat and seeraga samba together in a sharp curd-and-lemon masala using the absorption method", spice_level="Hot", cook_time=50),
        biryani("Ambur Biryani", "Indian", "Ambur, Tamil Nadu", "Chicken", "Seeraga samba rice", [i("Dried red chilli paste", 35, "g"), i("Curd", 160, "g"), i("Curry leaves", 12, "g")], "Build the masala around soaked red-chilli paste, cook the chicken, then combine with separately three-quarter-cooked seeraga samba", spice_level="Hot", cook_time=50),
        biryani("Chettinad Chicken Biryani", "Indian", "Chettinad, Tamil Nadu", "Chicken", "Seeraga samba rice", [i("Fennel seed", 10, "g"), i("Black stone flower", 2, "g"), i("Coconut milk", 220, "ml")], "Roast and grind Chettinad spices, fry them with chicken, and absorb coconut milk into seeraga samba rice", spice_level="Hot", cook_time=55),
        biryani("Sindhi Biryani", "Pakistani", "Sindh", "Chicken", "Basmati rice", [i("Potato", 350, "g"), i("Dried plum", 45, "g"), i("Green chilli", 30, "g")], "Cook a hot, tangy masala with potato, tomato and dried plum before layering it generously with rice", spice_level="Hot", cook_time=60),
        biryani("Bombay Biryani", "Indian", "Mumbai", "Chicken", "Basmati rice", [i("Potato", 350, "g"), i("Dried plum", 35, "g"), i("Kewra water", 12, "ml")], "Prepare the sweet-tart potato and chicken masala, then layer with rice and a restrained splash of kewra", spice_level="Medium", cook_time=60),
        biryani("Bhatkali Biryani", "Indian", "Bhatkal, Karnataka", "Chicken", "Basmati rice", [i("Curry leaves", 12, "g"), i("Green chilli", 25, "g"), i("Tomato", 250, "g")], "Cook the chicken in a deeply reduced onion-tomato masala with very little powdered spice before layering", spice_level="Hot", cook_time=60),
        biryani("Beary Biryani", "Indian", "Coastal Karnataka", "Mutton", "Jeerakasala rice", [i("Coconut", 80, "g"), i("Fennel seed", 9, "g"), i("Green chilli", 25, "g")], "Braise mutton in a fresh coconut, fennel and green-chilli masala, then finish with short-grain rice", spice_level="Medium", cook_time=80),
        biryani("Chicken Dum Biryani", "South Asian", "South Asia", "Chicken", "Basmati rice", [i("Biryani masala", 28, "g"), i("Lemon juice", 30, "ml"), i("Saffron milk", 70, "ml")], "Cook the chicken masala until nearly done, layer with parboiled rice, seal the lid and finish entirely in trapped steam", cook_time=65),
        biryani("Mutton Dum Biryani", "South Asian", "South Asia", "Mutton", "Basmati rice", [i("Biryani masala", 30, "g"), i("Lemon juice", 30, "ml"), i("Saffron milk", 70, "ml")], "Slow-braise the mutton until tender, reduce its gravy, then layer and seal with parboiled rice for dum", cook_time=90),
        biryani("Beef Biryani", "South Asian", "South Asia", "Beef", "Basmati rice", [i("Tomato", 220, "g"), i("Green chilli", 20, "g"), i("Biryani masala", 30, "g")], "Braise beef in the tomato masala until fork-tender before layering so the rice never waits for tough meat", spice_level="Hot", cook_time=95),
        biryani("Fish Biryani", "South Asian", "Coastal South Asia", "Fish", "Basmati rice", [i("Lemon juice", 40, "ml"), i("Fennel seed", 8, "g"), i("Tomato", 180, "g")], "Sear the marinated fish briefly, make the masala separately, then layer gently so the fish stays intact", cook_time=45),
        biryani("Prawn Biryani", "South Asian", "Coastal South Asia", "Prawn", "Basmati rice", [i("Lemon juice", 35, "ml"), i("Tomato", 180, "g"), i("Fennel seed", 8, "g")], "Cook the prawn only until partly opaque, remove it, reduce the masala, and return it during the short dum", cook_time=40),
        biryani("Egg Biryani", "Indian", "South India", "Egg", "Basmati rice", [i("Tomato", 180, "g"), i("Biryani masala", 24, "g"), i("Green chilli", 18, "g")], "Score and lightly fry boiled eggs, build a tomato masala, then nestle the eggs between rice layers", diet_type="Ovo-vegetarian", cook_time=45),
        biryani("Vegetable Biryani", "Indian", "South Asia", "None", "Basmati rice", [i("Cauliflower", 180, "g"), i("Carrot", 140, "g"), i("Green peas", 100, "g")], "Cook firm vegetables only halfway in the masala, then layer with parboiled rice so each vegetable keeps its shape", diet_type="Vegetarian", cook_time=50),
    ]
