from app.seeders.catalog_helpers import ingredient as i
from app.seeders.catalog_helpers import recipe


def classics_catalog():
    return [
        # Rice dishes outside biryani
        recipe("Sri Lankan Yellow Rice", "sri-lankan-rice", "Rice Dishes", "Fragrant Sri Lankan celebration rice coloured with turmeric and cooked with pandan, cinnamon and coconut milk.", [i("Basmati rice", 500, "g"), i("Coconut milk", 300, "ml"), i("Water", 400, "ml"), i("Onion", 150, "g"), i("Ghee", 45, "ml"), i("Turmeric", 5, "g"), i("Pandan leaf", 2, "piece"), i("Cinnamon", 4, "g"), i("Salt", 10, "g")], ["Rinse and drain the rice.", "Fry onion, cinnamon and pandan in ghee until fragrant.", "Add turmeric and rice and turn gently until every grain is coated.", "Add coconut milk, water and salt; bring once to a boil.", "Cover and cook over low heat until absorbed, then rest 10 minutes and fluff."], cuisine="Sri Lankan", region="Sri Lanka", protein="None", diet_type="Vegetarian", prep_time=15, cook_time=30, spice_level="Mild", tags=["rice", "celebration", "sri lankan"]),
        recipe("Coconut Rice", "sri-lankan-rice", "Rice Dishes", "Tender rice cooked with coconut milk and a curry-leaf mustard temper.", [i("Long-grain rice", 500, "g"), i("Coconut milk", 400, "ml"), i("Water", 350, "ml"), i("Mustard seed", 6, "g"), i("Curry leaves", 12, "g"), i("Grated coconut", 80, "g"), i("Oil", 30, "ml"), i("Salt", 10, "g")], ["Rinse rice until the water is nearly clear.", "Cook rice with coconut milk, water and salt over low heat.", "Rest covered after the liquid is absorbed.", "Temper mustard seed and curry leaves in oil, then toast grated coconut lightly.", "Fold the temper through the rice without crushing the grains."], cuisine="South Asian", region="South India and Sri Lanka", protein="None", diet_type="Vegan", prep_time=10, cook_time=30, spice_level="Mild", tags=["rice", "coconut", "vegan"]),
        recipe("Ghee Rice", "pulao-pilaf", "Rice Dishes", "South Indian ghee rice perfumed with whole spices, onions and cashews.", [i("Basmati rice", 500, "g"), i("Water", 750, "ml"), i("Ghee", 70, "ml"), i("Onion", 180, "g"), i("Cashew", 50, "g"), i("Cinnamon", 4, "g"), i("Cardamom", 4, "g"), i("Clove", 3, "g"), i("Salt", 10, "g")], ["Soak rice for 20 minutes and drain.", "Fry cashews in ghee and reserve them.", "Fry onion and whole spices until the onion is golden.", "Add rice and turn until glossy, then add measured water and salt.", "Cook covered on low heat, rest, fluff and finish with cashews."], cuisine="South Indian", region="Kerala and Tamil Nadu", protein="None", diet_type="Vegetarian", prep_time=25, cook_time=25, spice_level="Mild", tags=["rice", "ghee", "festive"]),
        recipe("Jeera Rice", "pulao-pilaf", "Rice Dishes", "Separate basmati grains tempered with cumin and ghee.", [i("Basmati rice", 500, "g"), i("Water", 750, "ml"), i("Cumin seed", 10, "g"), i("Ghee", 45, "ml"), i("Bay leaf", 2, "piece"), i("Salt", 10, "g")], ["Soak and drain basmati rice.", "Temper cumin and bay leaf in hot ghee until aromatic, not dark.", "Add rice and coat each grain in ghee.", "Pour in measured water and salt, cover, and cook over low heat.", "Rest covered for 10 minutes before fluffing."], cuisine="Indian", region="North India", protein="None", diet_type="Vegetarian", prep_time=25, cook_time=25, spice_level="Mild", tags=["rice", "cumin", "side dish"]),
        recipe("Vegetable Pulao", "pulao-pilaf", "Rice Dishes", "One-pot basmati pulao with vegetables and restrained whole spices.", [i("Basmati rice", 500, "g"), i("Mixed vegetables", 450, "g"), i("Water", 800, "ml"), i("Onion", 180, "g"), i("Ghee", 50, "ml"), i("Cumin seed", 8, "g"), i("Garam masala", 8, "g"), i("Salt", 10, "g")], ["Soak rice and cut vegetables evenly.", "Fry cumin and onion in ghee until lightly golden.", "Add firm vegetables and sauté briefly with garam masala.", "Add drained rice, measured water and salt.", "Cook by absorption, rest covered, and fluff gently."], cuisine="Indian", region="South Asia", protein="None", diet_type="Vegetarian", prep_time=20, cook_time=30, spice_level="Mild", tags=["pulao", "rice", "vegetarian"]),
        recipe("Chicken Pulao", "pulao-pilaf", "Rice Dishes", "Gentle chicken pulao in which rice absorbs a seasoned chicken stock.", [i("Basmati rice", 500, "g"), i("Chicken", 700, "g"), i("Chicken stock", 800, "ml"), i("Onion", 200, "g"), i("Yogurt", 150, "g"), i("Ghee", 55, "ml"), i("Cumin seed", 8, "g"), i("Garam masala", 10, "g"), i("Salt", 11, "g")], ["Brown chicken lightly with onion and whole spices.", "Add yogurt gradually and cook until it coats the chicken.", "Add stock and simmer until the chicken is nearly cooked.", "Add soaked rice and adjust the liquid to the measured amount.", "Cook covered by absorption, verify chicken doneness, then rest and fluff."], cuisine="South Asian", region="South Asia", protein="Chicken", prep_time=25, cook_time=45, spice_level="Medium", tags=["pulao", "chicken", "one pot"]),
        recipe("Classic Rice Pilaf", "pulao-pilaf", "Rice Dishes", "Buttery pilaf with toasted rice, aromatic vegetables and stock.", [i("Long-grain rice", 500, "g"), i("Vegetable stock", 800, "ml"), i("Onion", 150, "g"), i("Celery", 80, "g"), i("Butter", 55, "g"), i("Bay leaf", 2, "piece"), i("Black pepper", 5, "g"), i("Salt", 10, "g")], ["Sweat onion and celery in butter without colouring.", "Add rice and toast until the grains smell nutty and look translucent at the edges.", "Add hot stock, bay leaf, salt and pepper.", "Cover and cook gently until absorbed.", "Rest off heat, remove bay leaf and fluff."], cuisine="International", region="Mediterranean", protein="None", diet_type="Vegetarian", prep_time=15, cook_time=30, spice_level="Mild", tags=["pilaf", "rice", "side dish"]),
        recipe("Seafood Paella", "pulao-pilaf", "Rice Dishes", "Spanish saffron rice cooked uncovered with staged seafood and a toasted socarrat base.", [i("Bomba rice", 500, "g"), i("Mixed seafood", 700, "g"), i("Fish stock", 1200, "ml"), i("Tomato", 250, "g"), i("Olive oil", 60, "ml"), i("Smoked paprika", 10, "g"), i("Saffron", 1, "g"), i("Green bean", 180, "g"), i("Salt", 10, "g")], ["Warm stock with saffron.", "Sear seafood briefly in the paella pan and reserve delicate pieces.", "Cook tomato, paprika and beans into a concentrated sofrito.", "Add rice in an even layer, pour in stock, and do not stir after it settles.", "Return seafood in stages, cook until rice is tender, then raise heat briefly for socarrat and rest."], cuisine="Spanish", region="Valencia", protein="Seafood", difficulty="Advanced", prep_time=25, cook_time=45, spice_level="Mild", tags=["paella", "rice", "seafood"]),
        recipe("Kiribath", "sri-lankan-rice", "Rice Dishes", "Sri Lankan milk rice cooked until soft with coconut milk, pressed and cut into diamonds.", [i("Kekulu rice", 500, "g"), i("Water", 900, "ml"), i("Coconut milk", 450, "ml"), i("Salt", 9, "g")], ["Rinse rice and cook with water until very soft and most liquid is absorbed.", "Warm coconut milk with salt separately.", "Stir coconut milk into the soft rice and cook on low until thick and cohesive.", "Spread on a lightly moistened tray and flatten evenly.", "Cool just enough to set, then cut into diamonds with a wet knife."], cuisine="Sri Lankan", region="Sri Lanka", protein="None", diet_type="Vegan", prep_time=10, cook_time=40, spice_level="None", tags=["kiribath", "milk rice", "new year"]),

        # Roti and breads
        recipe("Godamba Roti", "roti-breads", "Breads", "Thin, elastic Sri Lankan flatbread used for kottu and stuffed roti.", [i("Wheat flour", 500, "g"), i("Water", 280, "ml"), i("Oil", 90, "ml"), i("Salt", 9, "g")], ["Mix flour, salt and water into a soft dough.", "Knead until elastic, divide into balls, coat generously in oil and rest at least 2 hours.", "Stretch one ball paper-thin on an oiled surface without tearing.", "Fold or transfer to a hot griddle and cook briefly on both sides so it remains pliable."], cuisine="Sri Lankan", region="Sri Lanka", protein="None", diet_type="Vegan", difficulty="Advanced", prep_time=150, cook_time=20, spice_level="None", tags=["roti", "godamba", "flatbread"]),
        recipe("Plain Roti", "roti-breads", "Breads", "Simple unleavened wheat roti cooked on a dry griddle.", [i("Whole-wheat flour", 500, "g"), i("Water", 300, "ml"), i("Oil", 25, "ml"), i("Salt", 8, "g")], ["Mix flour and salt, then add water gradually to form a soft dough.", "Knead smooth, cover and rest 25 minutes.", "Divide, dust lightly and roll into even rounds.", "Cook on a hot dry griddle until bubbles form and both sides show brown spots."], cuisine="South Asian", region="South Asia", protein="None", diet_type="Vegan", prep_time=35, cook_time=20, spice_level="None", tags=["roti", "flatbread", "everyday"]),
        recipe("Pol Roti", "roti-breads", "Breads", "Sri Lankan coconut roti with grated coconut and optional green chilli.", [i("Wheat flour", 400, "g"), i("Grated coconut", 220, "g"), i("Onion", 100, "g"), i("Green chilli", 15, "g"), i("Water", 220, "ml"), i("Salt", 9, "g")], ["Mix flour, coconut, onion, chilli and salt evenly.", "Add water gradually and knead into a firm but pliable dough.", "Rest 15 minutes, divide and pat into thick rounds.", "Cook over medium heat, turning often, until cooked through with toasted spots."], cuisine="Sri Lankan", region="Sri Lanka", protein="None", diet_type="Vegan", prep_time=25, cook_time=20, spice_level="Medium", tags=["pol roti", "coconut", "breakfast"]),
        recipe("Chapati", "roti-breads", "Breads", "Soft whole-wheat chapati puffed on a hot tawa.", [i("Atta flour", 500, "g"), i("Water", 320, "ml"), i("Oil", 15, "ml"), i("Salt", 7, "g")], ["Combine atta and salt and knead with water into a soft smooth dough.", "Rest covered for 30 minutes.", "Roll small portions thin and even using minimal dry flour.", "Cook on a hot tawa, turn at the first bubbles, and press gently to encourage puffing."], cuisine="Indian", region="India", protein="None", diet_type="Vegan", prep_time=40, cook_time=20, spice_level="None", tags=["chapati", "atta", "flatbread"]),
        recipe("Layered Paratha", "roti-breads", "Breads", "Flaky layered paratha made by folding a lightly oiled wheat dough.", [i("Wheat flour", 500, "g"), i("Water", 290, "ml"), i("Ghee", 80, "g"), i("Salt", 8, "g")], ["Knead flour, salt and water into a supple dough and rest 30 minutes.", "Roll thin, brush with ghee, pleat or coil, and rest again.", "Roll the coil without crushing all the layers.", "Cook on a medium-hot griddle with ghee until both sides are crisp and layered."], cuisine="South Asian", region="South Asia", protein="None", diet_type="Vegetarian", difficulty="Medium", prep_time=60, cook_time=25, spice_level="None", tags=["paratha", "layered", "flatbread"]),
        recipe("Naan", "roti-breads", "Breads", "Soft leavened naan cooked at intense heat for blistered edges.", [i("Wheat flour", 500, "g"), i("Yogurt", 120, "g"), i("Water", 220, "ml"), i("Active dry yeast", 7, "g"), i("Sugar", 10, "g"), i("Salt", 8, "g")], ["Activate yeast with warm water and sugar.", "Knead with flour, yogurt and salt into a soft dough and rise until doubled.", "Divide and rest, then stretch into teardrops.", "Cook against a very hot tandoor surface or on a hot skillet and char briefly under a grill."], cuisine="Indian", region="North India", protein="None", diet_type="Vegetarian", difficulty="Medium", prep_time=100, cook_time=15, spice_level="None", tags=["naan", "leavened", "tandoor"]),
        recipe("Butter Naan", "roti-breads", "Breads", "Leavened naan brushed with butter immediately after cooking.", [i("Wheat flour", 500, "g"), i("Yogurt", 120, "g"), i("Water", 220, "ml"), i("Active dry yeast", 7, "g"), i("Butter", 70, "g"), i("Salt", 8, "g")], ["Make and rise a soft yogurt-enriched yeast dough.", "Divide, rest and stretch each piece without knocking out every bubble.", "Cook at very high heat until puffed and spotted.", "Brush with melted butter while hot and serve immediately."], cuisine="Indian", region="North India", protein="None", diet_type="Vegetarian", prep_time=100, cook_time=15, spice_level="None", tags=["naan", "butter", "tandoor"]),
        recipe("Garlic Naan", "roti-breads", "Breads", "Naan topped with fresh garlic, coriander and butter.", [i("Wheat flour", 500, "g"), i("Yogurt", 120, "g"), i("Water", 220, "ml"), i("Active dry yeast", 7, "g"), i("Garlic", 35, "g"), i("Coriander leaves", 25, "g"), i("Butter", 55, "g"), i("Salt", 8, "g")], ["Rise the yogurt and yeast naan dough until doubled.", "Press chopped garlic and coriander onto each stretched naan with damp fingers.", "Cook topping-side toward intense heat until blistered and fragrant.", "Brush with butter after cooking so the garlic does not burn in the pan."], cuisine="Indian", region="North India", protein="None", diet_type="Vegetarian", prep_time=100, cook_time=15, spice_level="Mild", tags=["naan", "garlic", "tandoor"]),
        recipe("Sri Lankan Stuffed Roti", "roti-breads", "Breads", "Pan-cooked godamba parcels filled with a dry curried potato mixture.", [i("Godamba dough", 600, "g"), i("Potato", 500, "g"), i("Onion", 160, "g"), i("Curry leaves", 12, "g"), i("Roasted curry powder", 15, "g"), i("Oil", 40, "ml"), i("Salt", 9, "g")], ["Boil potato until tender and drain thoroughly.", "Cook onion, curry leaves and spices, then mash in potato to make a dry filling and cool it.", "Stretch rested godamba dough thin, place filling in the centre and fold into a sealed rectangle.", "Cook on a medium griddle, turning all sides until the dough is browned and the centre hot."], cuisine="Sri Lankan", region="Sri Lanka", protein="None", diet_type="Vegan", difficulty="Medium", prep_time=60, cook_time=30, spice_level="Medium", tags=["stuffed roti", "street food", "potato"]),
    ]
